hm update

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -28,26 +28,26 @@ jobs:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           
 
-      - name: Run SonarQube scan
-        run: |
-          mvn sonar:sonar -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} -Dsonar.login=${{ secrets.SONAR_TOKEN }}
+#      - name: Run SonarQube scan
+#        run: |
+#          mvn sonar:sonar -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} -Dsonar.login=${{ secrets.SONAR_TOKEN }}
     
-          - name: Check SonarQube Quality Gate
-          id: quality_gate
-          run: |
-            # Wait a few seconds to ensure SonarQube analysis is complete
-            sleep 30
-            # Retrieve the Quality Gate status
-            status=$(curl -s -X GET -u ${{ secrets.SONAR_TOKEN }}: \
-              "${{ secrets.SONAR_HOST_URL }}/api/qualitygates/project_status?projectKey=your_project_key" | \
-              jq -r '.projectStatus.status')
+#          - name: Check SonarQube Quality Gate
+#          id: quality_gate
+#          run: |
+#            # Wait a few seconds to ensure SonarQube analysis is complete
+#            sleep 30
+#            # Retrieve the Quality Gate status
+#            status=$(curl -s -X GET -u ${{ secrets.SONAR_TOKEN }}: \
+#              "${{ secrets.SONAR_HOST_URL }}/api/qualitygates/project_status?projectKey=your_project_key" | \
+#              jq -r '.projectStatus.status')
     
-            if [ "$status" != "OK" ]; then
-              echo "SonarQube Quality Gate failed. Status: $status"
-              exit 1
-            else
-              echo "SonarQube Quality Gate passed."
-            fi
+#            if [ "$status" != "OK" ]; then
+#              echo "SonarQube Quality Gate failed. Status: $status"
+#              exit 1
+#            else
+#              echo "SonarQube Quality Gate passed."
+#            fi
 
       - name: Cache Maven packages
         uses: actions/cache@v4
@@ -84,18 +84,27 @@ jobs:
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: ${{ secrets.AWS_REGION }}
 
-      - name: Set up kubectl
-        uses: azure/setup-kubectl@v1
-        with:
-          version: '1.24.0'
+#      - name: Set up kubectl
+#        uses: azure/setup-kubectl@v1
+#        with:
+#          version: '1.28.0'
 
-      - name: Update kubeconfig
-        run: |
-          aws eks update-kubeconfig --name PrdEksCluster
+#      - name: Update kubeconfig
+#        run: |
+#          aws eks update-kubeconfig --name PrdEksCluster
 
-      - name: Deploy to EKS
-        run: |
-          helm upgrade --install myapp ./RBCharts \
-            --set image.repository=naveenvilas/my-spring-boot-webapp \
-            --set image.tag=latest \
-            --namespace default
+ #     - name: Deploy to EKS
+ #       run: |
+ #         helm upgrade --install myapp ./RBCharts \
+ #           --set image.repository=naveenvilas/my-spring-boot-webapp \
+ #           --set image.tag=latest \
+ #           --namespace default
+
+      - name: Setup Helm
+        uses: azure/setup-helm@v1
+
+      - name: Helm Lint
+        run: helm lint ./RBCharts
+
+      - name: Helm Template
+        run: helm template ./RBCharts --values ./RBCharts/values.yaml
