sonarScan stage added

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -17,6 +17,27 @@ jobs:
           distribution: 'temurin'  # Specify the JDK distribution
           java-version: '17'
 
+      - name: Run SonarQube scan
+        run: |
+          mvn sonar:sonar -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} -Dsonar.login=${{ secrets.SONAR_TOKEN }}
+    
+          - name: Check SonarQube Quality Gate
+          id: quality_gate
+          run: |
+            # Wait a few seconds to ensure SonarQube analysis is complete
+            sleep 30
+            # Retrieve the Quality Gate status
+            status=$(curl -s -X GET -u ${{ secrets.SONAR_TOKEN }}: \
+              "${{ secrets.SONAR_HOST_URL }}/api/qualitygates/project_status?projectKey=your_project_key" | \
+              jq -r '.projectStatus.status')
+    
+            if [ "$status" != "OK" ]; then
+              echo "SonarQube Quality Gate failed. Status: $status"
+              exit 1
+            else
+              echo "SonarQube Quality Gate passed."
+            fi
+
       - name: Cache Maven packages
         uses: actions/cache@v4
         with:
@@ -25,17 +46,6 @@ jobs:
           restore-keys: |
             ${{ runner.os }}-maven-
 
-     # - name: Build with Maven
-     #   run: mvn clean install
-
-     # - name: Run Tests
-     #   run: mvn test
-
-    #   - name: Run Spring Boot Application
-    #   run: mvn spring-boot:run
-
-      #- name: Build with Maven
-      #  run: mvn clean package
 
       - name: Build with Maven
         run: mvn package -DskipTests
